### ISSUE TITLE
SET_TYPE_POSOBJ no longer exists

### ISSUE THREAD

**Issue by ChrisJefferson** [gap-packages/cvec#7]
cvec tries to call the macro SET_TYPE_POSOBJ, which is no longer defined in GAP.

This is also used by the `float` package, so it might be easier to reintroduce it to GAP, but either way it should be fixed.

**Comment by fingolfin** [comment]
But `SET_TYPE_POSOBJ` *is* being defined by GAP, in `src/objects.h`.

However, I just tried to compile cvec, and it turns out `SET_TYPE_DATOBJ` is the problem (I guess that shows that it's always best to report actual error messages / logs, instead of paraphrasing the issue ;-).

I'll look into it. Thanks for the report!

**Comment by fingolfin** [comment]
See https://github.com/gap-system/gap/pull/1365
